# Generated by Django 4.2 on 2023-09-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('Discount_Deal', models.CharField(choices=[('HOT ARRIVAL', 'HOT ARRIVAL'), ('NWE ARRIVAL', 'NEW ARRIVAL')], max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
