# Generated by Django 4.2 on 2023-09-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
