# Generated by Django 4.2 on 2023-09-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0002_slider_discount_alter_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='noprofile.png', upload_to='slider'),
        ),
    ]
