# Generated by Django 4.2 on 2023-09-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0003_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='noprofile.png', upload_to='BannerArea')),
                ('Discount_Deal', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BannerArea',
                'verbose_name_plural': 'BannerAreas',
            },
        ),
    ]
