# Generated by Django 4.2 on 2023-09-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0004_bannerarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerarea',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
