# Generated by Django 4.2 on 2023-09-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0008_alter_product_description_alter_product_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.TextField(max_length=2000),
        ),
    ]
