# Generated by Django 4.2 on 2023-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0009_alter_product_description_alter_product_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='red', max_length=12),
        ),
    ]
