# Generated by Django 4.2 on 2023-10-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0010_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvec.product')),
            ],
            options={
                'verbose_name': 'Accessories',
                'verbose_name_plural': 'Accessoriess',
            },
        ),
    ]
