# Generated by Django 4.2 on 2023-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0011_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='name',
            field=models.CharField(default='accessory', max_length=100),
        ),
    ]
