# Generated by Django 4.2 on 2023-10-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0012_accessories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(default='red', max_length=12),
        ),
        migrations.AddField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
