# Generated by Django 4.2 on 2023-10-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0013_accessories_color_accessories_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
    ]
