# Generated by Django 4.2 on 2023-10-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0014_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
