# Generated by Django 4.2 on 2023-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvec', '0015_product_packing_cost_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codon_copon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condon', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Codon_copon',
                'verbose_name_plural': 'Codon_copons',
            },
        ),
    ]
